// Hardcoded fallback services for instant display when network is unavailable
// These are from the production database and should be updated when services change
// Used as immediate fallback before network fetch completes

export interface FallbackService {
  id: string;
  name: string;
  base_price: number;
  description: string | null;
  duration_minutes: number | null;
  is_active: boolean;
  is_visible: boolean;
  pricing_config?: any;
  sort_order: number;
  image_url: string | null;
  created_at: string | null;
}

export const FALLBACK_SERVICES: FallbackService[] = [
  {
    id: 'a50013bc-ee03-4452-b3ec-1683094d787a',
    name: 'Mount TV',
    base_price: 90,
    description: 'Professional TV wall mounting with perfect positioning',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 1,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/2ep427hz12t-1772102991053.jpg',
    created_at: null,
  },
  {
    id: '1e602b4f-8b3c-4a5e-8838-1dc14539bd67',
    name: 'TV Wall Mounting',
    base_price: 185,
    description: 'Professional TV wall mounting service with cable management',
    duration_minutes: 120,
    is_active: true,
    is_visible: false,
    sort_order: 2,
    image_url: null,
    created_at: null,
  },
  {
    id: '39927b48-3d6b-4a22-a851-4e3b315a5394',
    name: 'Buy Full Motion Mount (Living Room)',
    base_price: 80,
    description: 'Swivels to face the kitchen, installs quickly and supports up to an 85" TV. Always reaches both studs.',
    duration_minutes: 1,
    is_active: true,
    is_visible: true,
    sort_order: 3,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/x3qgspnnwd-1772106862580.jpg',
    created_at: null,
  },
  {
    id: '5b5f5da8-ab42-44f2-9437-686df5bd7798',
    name: 'TV Setup & Configuration',
    base_price: 100,
    description: 'Complete TV setup including streaming services and sound system',
    duration_minutes: 90,
    is_active: true,
    is_visible: false,
    sort_order: 4,
    image_url: null,
    created_at: null,
  },
  {
    id: 'a202a6d4-68b1-4bbf-95f0-4bfe3d3b6f3e',
    name: 'Cable Management',
    base_price: 75,
    description: 'Hide and organize all TV and entertainment system cables',
    duration_minutes: 60,
    is_active: true,
    is_visible: false,
    sort_order: 5,
    image_url: null,
    created_at: null,
  },
  {
    id: 'f1a00a20-72f4-4a66-b126-ede6a7c94a2d',
    name: 'Buy Flat Tilt Mount (Bedroom)',
    base_price: 50,
    description: 'Low-profile tilting flat mount that can tilt slightly down for optimal viewing lying down.',
    duration_minutes: 1,
    is_active: true,
    is_visible: true,
    sort_order: 6,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/66mdt667l27-1772106872654.jpg',
    created_at: null,
  },
  {
    id: '42cccc21-1eff-4d7c-9d0b-5651a99ba005',
    name: 'Sound System Installation',
    base_price: 200,
    description: 'Install and configure home theater sound system',
    duration_minutes: 150,
    is_active: true,
    is_visible: false,
    sort_order: 7,
    image_url: null,
    created_at: null,
  },
  {
    id: '7830bb03-1489-4be1-9ec1-ef955fa9f457',
    name: 'Cable Concealment',
    base_price: 20,
    description: 'Clean cable management with decorative covers',
    duration_minutes: 15,
    is_active: true,
    is_visible: true,
    sort_order: 8,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/85jb55vgsst-1772103814827.JPG',
    created_at: null,
  },
  {
    id: 'c3d3e874-da2d-49ef-9152-53bcb6fe9036',
    name: 'In-Wall Cable Concealment',
    base_price: 60,
    description: 'Basic in-wall cable concealment',
    duration_minutes: 30,
    is_active: true,
    is_visible: true,
    sort_order: 9,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/ybpjgns8p8j-1772056953789.JPG',
    created_at: null,
  },
  {
    id: '5e5ca4b0-e17f-4f72-98a4-9b8c1140d959',
    name: 'Smart Home Integration',
    base_price: 125,
    description: 'Connect TV to smart home ecosystem',
    duration_minutes: 90,
    is_active: true,
    is_visible: false,
    sort_order: 10,
    image_url: null,
    created_at: null,
  },
  {
    id: '83d86a4c-626b-45e2-bbff-f9e8368c95a7',
    name: 'In-Wall Fire Safe Cable Concealment',
    base_price: 120,
    description: 'Fire-rated in-wall cable concealment system',
    duration_minutes: 45,
    is_active: true,
    is_visible: true,
    sort_order: 11,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/j2uhsihdu0h-1772101288178.JPG',
    created_at: null,
  },
  {
    id: 'd767d150-8d93-4d24-a96d-db9a80a67bb2',
    name: 'General Mounting',
    base_price: 85,
    description: 'Professionally mounted curtains, shelves, paintings and mirrors by the hour.',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 12,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/my4uqv84sm-1760066362316.jpg',
    created_at: null,
  },
  {
    id: 'd69350be-c842-4c8a-803e-e94c954a147e',
    name: 'Furniture Assembly',
    base_price: 65,
    description: 'Professional furniture assembly per hour\n*One hour minimum per piece',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 13,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/pt1bew459g-1759972777522.jpg',
    created_at: null,
  },
  {
    id: '8dfc0def-14e0-44ef-a43f-107520f5d3ee',
    name: 'Custom Lighting',
    base_price: 100,
    description: 'Customize your living room and deck lighting',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 14,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/4gwz1ggl036-1759972523307.jpg',
    created_at: null,
  },
  {
    id: '4bb594da-9490-4767-8b12-6cee61842b23',
    name: 'Luxury Accent Wall',
    base_price: 800,
    description: 'Cover an accent wall with beautiful designs: Living room or bedroom.',
    duration_minutes: 240,
    is_active: true,
    is_visible: true,
    sort_order: 15,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/ldhfcu81qlk-1759803068303.png',
    created_at: null,
  },
  {
    id: 'e91899b6-6827-41b8-b79b-26e71e2ad27b',
    name: 'Luxury Deck',
    base_price: 300,
    description: 'Square wood tiles laid to cover entire deck',
    duration_minutes: 120,
    is_active: true,
    is_visible: true,
    sort_order: 16,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/h9pzylw53zm-1759977408119.jpg',
    created_at: null,
  },
  {
    id: '9a9c0005-dd3b-4ef1-a223-194f84ca41b6',
    name: 'Luxury Garden',
    base_price: 500,
    description: 'Enticing seasonal Luxury garden with spillers, fillers and thrillers placed on your deck in window boxes.',
    duration_minutes: 360,
    is_active: true,
    is_visible: true,
    sort_order: 17,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/gop0es9o50h-1759905557537.jpg',
    created_at: null,
  },
  {
    id: '0a15d0ac-57da-4139-a067-232eafc9ee8c',
    name: 'Hire Second Technician',
    base_price: 75,
    description: 'Additional technician for complex installations',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 18,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/eklpmf3jtk-1760067810821.jpg',
    created_at: null,
  },
  {
    id: 'cdf843ae-fdca-4c8e-b6a8-4fae4626e916',
    name: 'Distant Address Fee',
    base_price: 35,
    description: 'If the address is excessively far away',
    duration_minutes: 45,
    is_active: true,
    is_visible: true,
    sort_order: 19,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/77cciz9x3eh-1760066991690.jpg',
    created_at: null,
  },
  {
    id: '0ecddabe-486a-4e24-b87b-a6d8a844b09c',
    name: 'Dismount TV',
    base_price: 35,
    description: '',
    duration_minutes: 15,
    is_active: true,
    is_visible: true,
    sort_order: 20,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/vvrvpnqtcc-1759977027015.jpg',
    created_at: null,
  },
  {
    id: '63b3e668-8e02-4255-bb5d-0f21eb01e216',
    name: 'Transport TV',
    base_price: 35,
    description: '',
    duration_minutes: 30,
    is_active: true,
    is_visible: true,
    sort_order: 21,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/9q6j1xjgcj4-1772120187399.JPG',
    created_at: null,
  },
  {
    id: 'bfdb0ef4-4908-4595-95bc-e3cbded97e99',
    name: 'Move Outlet',
    base_price: 150,
    description: 'Removing an outlet only: charge $75',
    duration_minutes: 45,
    is_active: true,
    is_visible: true,
    sort_order: 22,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/m4ix4lqarw-1759969568441.jpg',
    created_at: null,
  },
  {
    id: '1b47852d-4cbf-439a-89dc-41bac8bcc20e',
    name: 'Frame Mount Add-on',
    base_price: 40,
    description: 'Specialized frame mounting service',
    duration_minutes: 15,
    is_active: true,
    is_visible: false,
    sort_order: 23,
    image_url: null,
    created_at: null,
  },
  {
    id: '81194c48-77a8-496e-9d87-f048fe501df0',
    name: 'Over 65" TV Add-on',
    base_price: 25,
    description: 'Additional charge for TVs over 65 inches',
    duration_minutes: 15,
    is_active: true,
    is_visible: false,
    sort_order: 24,
    image_url: null,
    created_at: null,
  },
  {
    id: 'b86fda8c-a667-4dee-b180-3c83d6329c3f',
    name: 'Brick/Steel/Concrete',
    base_price: 40,
    description: 'Additional charge for mounting on stone, brick, Steel or tile walls',
    duration_minutes: 30,
    is_active: true,
    is_visible: false,
    sort_order: 25,
    image_url: null,
    created_at: null,
  },
  {
    id: 'b87460f0-8b9e-457f-9aa2-9fb682e6fd1d',
    name: 'General Mounting 15 Minutes (Worker Only)',
    base_price: 21.25,
    description: 'Extra 15 minutes general mounting service',
    duration_minutes: 15,
    is_active: true,
    is_visible: true,
    sort_order: 26,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/ioxgifcc2in-1760067468574.png',
    created_at: null,
  },
  {
    id: '7b6b8941-7e37-49a7-b705-9764b6fc333d',
    name: 'Furniture Assembly 15 Minutes (Worker Only)',
    base_price: 16.25,
    description: 'Extra 15 minutes furniture assembly service',
    duration_minutes: 15,
    is_active: true,
    is_visible: true,
    sort_order: 27,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/u88fecxlevn-1760067595033.png',
    created_at: null,
  },
  {
    id: '3bcfc465-aa05-49a7-9bf9-8631fe2c54cb',
    name: 'Over 65" Modifier (Worker Only)',
    base_price: 25,
    description: "If the customer didn't specify.",
    duration_minutes: 25,
    is_active: true,
    is_visible: true,
    sort_order: 28,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/6cm29qf2gzt-1764500502052.jpg',
    created_at: null,
  },
  {
    id: '03c7f266-9e17-419c-9fed-6c549b2ed30c',
    name: 'Frame TV Modifier (Worker Only)',
    base_price: 40,
    description: "If the customer didn't specify for a frame.",
    duration_minutes: 15,
    is_active: true,
    is_visible: true,
    sort_order: 29,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/h10xptr3sm-1764500416812.jpg',
    created_at: null,
  },
  {
    id: 'c90596a9-1580-4342-843c-0eb6568d8d10',
    name: 'Steel Studs Modifier (Worker Only)',
    base_price: 40,
    description: 'In case you need to add it later',
    duration_minutes: 30,
    is_active: true,
    is_visible: true,
    sort_order: 30,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/9gib27eybtn-1764026321582.jpg',
    created_at: null,
  },
  {
    id: 'caf12ad9-43ed-4130-b9d3-a446fdb8a0b6',
    name: 'Mount Soundbar (Worker Only)',
    base_price: 40,
    description: 'Mount a soundbar.',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 31,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/0xwiimpk8foh-1764026330097.jpg',
    created_at: null,
  },
  {
    id: 'd326748d-bc2c-4cc2-a074-70dcbee51f83',
    name: 'HDMI Cable (Worker Only)',
    base_price: 15,
    description: "12' 4K braided HDMI cable",
    duration_minutes: 1,
    is_active: true,
    is_visible: true,
    sort_order: 33,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/e2ycpk69ter-1772103940654.JPG',
    created_at: null,
  },
  {
    id: '0f3d39e5-0bbc-4ae8-95a2-1c9e027c2f51',
    name: "6' Extension Cord (Worker Only)",
    base_price: 3,
    description: "Charge two for 12'",
    duration_minutes: 1,
    is_active: true,
    is_visible: true,
    sort_order: 34,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/vglsaajog-1772105203000.JPG',
    created_at: null,
  },
  {
    id: 'e341dafc-9f58-4915-89c5-e56944d4af03',
    name: 'Toggle Bolt (Worker Only)',
    base_price: 2,
    description: '',
    duration_minutes: 1,
    is_active: true,
    is_visible: true,
    sort_order: 35,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/0nsu21tj6ny-1772103904643.JPG',
    created_at: null,
  },
  {
    id: '41ec18d4-516b-4af6-9b05-e38b534923dd',
    name: 'Mount Soundbar',
    base_price: 40,
    description: 'Mount soundbar below or above TV',
    duration_minutes: 20,
    is_active: true,
    is_visible: false,
    sort_order: 36,
    image_url: null,
    created_at: null,
  },
  {
    id: 'b82985ac-13f6-4132-923e-3d3012eec2fb',
    name: 'Extra Charge (Worker Only)',
    base_price: 10,
    description: 'Parking with customer approval or other charges.',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 37,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/2azm87srpx3-1772105185944.JPG',
    created_at: null,
  },
  {
    id: 'c965531a-a2d3-42fe-86a6-3218d7445042',
    name: 'Supersize TV',
    base_price: 200,
    description: '',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 1000,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/tmi0xroucrn-1772104571738.jpg',
    created_at: null,
  },
  {
    id: '5bbd90ac-8472-45b8-9f81-81a759c9e302',
    name: 'Supersize TV With Crew',
    base_price: 300,
    description: '',
    duration_minutes: 60,
    is_active: true,
    is_visible: true,
    sort_order: 1000,
    image_url: 'https://ggvplltpwsnvtcbpazbe.supabase.co/storage/v1/object/public/service-images/8teuynthonk-1772104587751.JPG',
    created_at: null,
  },
];

// Legacy exports for backward compatibility
export const TV_MOUNTING_FALLBACK_SERVICES: Record<string, FallbackService> = {
  mountTv: FALLBACK_SERVICES.find(s => s.name === 'Mount TV')!,
  over65: FALLBACK_SERVICES.find(s => s.name === 'Over 65" TV Add-on')!,
  frameMount: FALLBACK_SERVICES.find(s => s.name === 'Frame Mount Add-on')!,
  soundbar: FALLBACK_SERVICES.find(s => s.name === 'Mount Soundbar')!,
  specialWall: FALLBACK_SERVICES.find(s => s.name === 'Brick/Steel/Concrete')!,
};

// Convert fallback services to array format for compatibility
export const getFallbackServicesArray = () => {
  return FALLBACK_SERVICES;
};
