// Export utilities for CSV and PDF generation

export const exportToCSV = (data: any[], filename: string) => {
  if (!data.length) return;

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header] || '';
        // Escape commas and quotes in CSV data
        return typeof value === 'string' && (value.includes(',') || value.includes('"'))
          ? `"${value.replace(/"/g, '""')}"`
          : value;
      }).join(',')
    )
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

export const exportToPDF = async (workers: any[], filename: string) => {
  // Create a simple HTML report for PDF generation
  const htmlContent = generateHTMLReport(workers);
  
  // Open print dialog (user can save as PDF)
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }
};

const generateHTMLReport = (workers: any[]) => {
  const timestamp = new Date().toLocaleDateString();
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Worker Service Areas Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .worker { margin-bottom: 30px; page-break-inside: avoid; }
        .worker-header { background-color: #f5f5f5; padding: 10px; margin-bottom: 10px; }
        .area { margin-left: 20px; margin-bottom: 10px; }
        .zip-codes { font-size: 12px; color: #666; margin-left: 10px; }
        .badge { 
          display: inline-block; 
          padding: 2px 8px; 
          background-color: #e2e8f0; 
          border-radius: 4px; 
          font-size: 12px; 
          margin-left: 10px;
        }
        .active { background-color: #10b981; color: white; }
        .inactive { background-color: #ef4444; color: white; }
        @media print {
          body { margin: 0; }
          .worker { page-break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Worker Service Areas Report</h1>
        <p>Generated on: ${timestamp}</p>
        <p>Total Workers: ${workers.length}</p>
      </div>
      
      ${workers.map(worker => `
        <div class="worker">
          <div class="worker-header">
            <h2>${worker.name}</h2>
            <span class="badge ${worker.is_active ? 'active' : 'inactive'}">
              ${worker.is_active ? 'Active' : 'Inactive'}
            </span>
            <p>Email: ${worker.email} | Phone: ${worker.phone || 'N/A'}</p>
            <p>Service Areas: ${worker.service_areas.length} | 
               Active Areas: ${worker.service_areas.filter((a: any) => a.is_active).length} |
               Total Zip Codes: ${worker.service_zipcodes.length}</p>
          </div>
          
          ${worker.service_areas.length === 0 ? 
            '<p style="margin-left: 20px; color: #666;">No service areas assigned</p>' :
            worker.service_areas.map((area: any) => `
              <div class="area">
                <h4>${area.area_name}
                  <span class="badge ${area.is_active ? 'active' : 'inactive'}">
                    ${area.is_active ? 'Active' : 'Inactive'}
                  </span>
                </h4>
                <p>Created: ${new Date(area.created_at).toLocaleDateString()}</p>
                <div class="zip-codes">
                  <strong>Zip Codes:</strong> 
                  ${worker.service_zipcodes
                    .filter((zip: any) => zip.service_area_id === area.id)
                    .map((zip: any) => zip.zipcode)
                    .join(', ') || 'None assigned'}
                </div>
              </div>
            `).join('')
          }
        </div>
      `).join('')}
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; text-align: center; color: #666;">
        <p>End of Report - Generated by Hero TV Mounting Admin Panel</p>
      </div>
    </body>
    </html>
  `;
};