// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List all active public services offered by Hero TV Mounting, including base price and pricing configuration.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("services").select("id, name, description, base_price, duration_minutes, pricing_config, is_active").eq("is_active", true);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { services: data }
    };
  }
});

// src/lib/mcp/tools/check-service-area.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var check_service_area_default = defineTool2({
  name: "check_service_area",
  title: "Check service area",
  description: "Check whether Hero TV Mounting services a given US ZIP code.",
  inputSchema: {
    zip_code: z.string().trim().regex(/^\d{5}$/, "Must be a 5-digit US ZIP code")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ zip_code }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("service_areas").select("zip_code, city, state, is_active").eq("zip_code", zip_code).eq("is_active", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const covered = !!data;
    return {
      content: [{
        type: "text",
        text: covered ? `Yes \u2014 ZIP ${zip_code} (${data.city}, ${data.state}) is in the service area.` : `No \u2014 ZIP ${zip_code} is not currently in the service area.`
      }],
      structuredContent: { covered, area: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hero-tv-mounting-mcp",
  title: "Hero TV Mounting MCP",
  version: "0.1.0",
  instructions: "Tools for Hero TV Mounting. Use `list_services` to see available TV mounting and related services with pricing. Use `check_service_area` to verify whether a US ZIP code is covered.",
  tools: [list_services_default, check_service_area_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
