// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggvplltpwsnvtcbpazbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndnBsbHRwd3NudnRjYnBhemJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTU5NjIsImV4cCI6MjA2NTA5MTk2Mn0.cbZ4kBKP7odpP9r1Qrg4G6CA8XdW7vLdKsqr6gE0j_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

// Auto-recover from stale auth refresh loops
let authFailureCount = 0;
const MAX_AUTH_FAILURES = 3;

supabase.auth.onAuthStateChange((event) => {
  if (event === 'TOKEN_REFRESHED') {
    authFailureCount = 0;
  } else if (event === 'SIGNED_OUT') {
    authFailureCount = 0;
  }
});

// Patch: detect repeated refresh failures and auto-signout
const originalRefresh = supabase.auth.refreshSession.bind(supabase.auth);
supabase.auth.refreshSession = async (...args) => {
  try {
    const result = await originalRefresh(...args);
    if (result.error) {
      authFailureCount++;
      console.warn(`[Auth Recovery] Refresh failed (${authFailureCount}/${MAX_AUTH_FAILURES}):`, result.error.message);
      if (authFailureCount >= MAX_AUTH_FAILURES) {
        console.warn('[Auth Recovery] Too many refresh failures, signing out stale session');
        authFailureCount = 0;
        await supabase.auth.signOut({ scope: 'local' });
      }
    } else {
      authFailureCount = 0;
    }
    return result;
  } catch (err) {
    authFailureCount++;
    console.warn(`[Auth Recovery] Refresh threw (${authFailureCount}/${MAX_AUTH_FAILURES}):`, err);
    if (authFailureCount >= MAX_AUTH_FAILURES) {
      console.warn('[Auth Recovery] Too many refresh failures, signing out stale session');
      authFailureCount = 0;
      try { await supabase.auth.signOut({ scope: 'local' }); } catch {}
    }
    throw err;
  }
};