// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggvplltpwsnvtcbpazbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndnBsbHRwd3NudnRjYnBhemJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTU5NjIsImV4cCI6MjA2NTA5MTk2Mn0.cbZ4kBKP7odpP9r1Qrg4G6CA8XdW7vLdKsqr6gE0j_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

// Stuck-auth detector: if we detect a stale session that can't refresh,
// automatically sign out after 15 seconds to break the infinite retry loop.
let stuckAuthTimer: ReturnType<typeof setTimeout> | null = null;
let lastSuccessfulAuth = Date.now();

supabase.auth.onAuthStateChange((event) => {
  if (event === 'TOKEN_REFRESHED' || event === 'SIGNED_IN') {
    lastSuccessfulAuth = Date.now();
    if (stuckAuthTimer) {
      clearTimeout(stuckAuthTimer);
      stuckAuthTimer = null;
    }
  } else if (event === 'SIGNED_OUT') {
    lastSuccessfulAuth = Date.now();
    if (stuckAuthTimer) {
      clearTimeout(stuckAuthTimer);
      stuckAuthTimer = null;
    }
  }
});

// Check on load: if there's a stored session, start the stuck detector
supabase.auth.getSession().then(({ data: { session } }) => {
  if (session) {
    // Give 15 seconds for a successful token refresh
    stuckAuthTimer = setTimeout(async () => {
      const timeSinceSuccess = Date.now() - lastSuccessfulAuth;
      if (timeSinceSuccess >= 14000) {
        console.warn('[Auth Recovery] No successful auth event in 15s, clearing stale session');
        try {
          await supabase.auth.signOut({ scope: 'local' });
        } catch (e) {
          console.warn('[Auth Recovery] signOut failed, clearing storage manually');
          Object.keys(localStorage).forEach((key) => {
            if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
              localStorage.removeItem(key);
            }
          });
        }
      }
    }, 15000);
  }
});